# Configuration Settings for ZED-F9P device

device: /dev/sensor_GPS

frame_id: gps
uart1:
  baudrate: 115200

dgnss_mode: 3               # Fixed mode

inf: 
  all: true                   # Whether to display all INF messages in console

# Enable u-blox message publishers
publish:
  all: true
  aid:
    hui: false

  nav:
    posecef: false

config_on_startup: false
